import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const PoppinsFont = Poppins({ subsets: ["latin"], weight: "600" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PoppinsFont.className}>{children}</body>
    </html>
  );
}
